config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("devices/", include("devices.urls", namespace="devices")),
    path("users/", include("users.urls", namespace="users")),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from devices import views as devices_views


app_name = "core"

urlpatterns = [
    path("", devices_views.HomeView, name="home")
]

devices/urls.py
from django.urls import path
from . import views

app_name = "devices"

urlpatterns = [
    path("ups/<int:pk>/", views.Ups_detail, name="ups_detail"),
    path("th/<int:pk>/", views.Th_detail, name="th_detail"),
    path("con/<int:pk>/", views.Con_detail, name="con_detail"),
    # path("Phone/<int:pk>/", views.Phone, name="phone"),
    path("search/", views.Search, name="search"),
    path("ups/", views.Ups, name="ups"),
    path("th/", views.Th, name="th"),
    path("con/", views.Con, name="conn"),
    path("phone_update/<int:pk>/", views.PhoneUpdateView.as_view(), name="phoneupdate"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView, name="logout")
]

templates/partials/footer.html
<h5>Footer입니다</h5>

templates/partials/header.html
<ul class="font-semibold flex items-center pl-6">

{% if user.is_authenticated %}
<li class="ml-8"><a href="{% url 'core:home' %}">전체</a></li>
<li class="ml-8"><a href="{% url 'devices:ups' %}">UPS</a></li>
<li class="ml-8"><a href="{% url 'devices:th' %}">온습도</a></li>
<li class="ml-8"><a href="{% url 'devices:conn' %}">기타장비</a></li>
<li class="ml-8"><a href="{% url 'users:logout' %}">Log Out</a></li>
{% else %}
<li class="ml-8"><a href="{% url 'users:login' %}">Log In</a></li>
{% endif %}
</ul>

templates/partials/message.html
{% if messages %}
<div class="bg-indigo-600">
    <div class="max-w-7xl mx-auto py-3 px-3 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between flex-wrap">
        <div class="w-0 flex-1 flex items-center">
          <span class="flex p-2 rounded-lg bg-indigo-800">
            <!-- Heroicon name: outline/speakerphone -->
            <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
            </svg>
          </span>
          <p class="ml-3 font-medium text-white truncate">
            <span class="md:hidden">
              We announced a new product!
            </span>
            {% for message in messages %}
            <span class="hidden md:inline">
                {{ message }}
            </span>
            {% endfor %}
          </p>
        </div>
        <div class="order-3 mt-2 flex-shrink-0 w-full sm:order-2 sm:mt-0 sm:w-auto">
          <a href="#" class="flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-indigo-600 bg-white hover:bg-indigo-50">
            Learn more
          </a>
        </div>
        <div class="order-2 flex-shrink-0 sm:order-3 sm:ml-3">
          <button type="button" class="-mr-1 flex p-2 rounded-md hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-white sm:-mr-2">
            <span class="sr-only">Dismiss</span>
            <!-- Heroicon name: outline/x -->
            <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
{% endif %}