config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("devices/", include("devices.urls", namespace="devices")),
    path("users/", include("users.urls", namespace="users")),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from devices import views as devices_views


app_name = "core"

urlpatterns = [
    path("", devices_views.HomeView, name="home")
]

devices/urls.py
from django.urls import path
from . import views

app_name = "devices"

urlpatterns = [
    path("ups/<int:pk>/", views.Ups_detail, name="ups_detail"),
    path("th/<int:pk>/", views.Th_detail, name="th_detail"),
    path("con/<int:pk>/", views.Con_detail, name="con_detail"),
    # path("Phone/<int:pk>/", views.Phone, name="phone"),
    path("search/", views.Search, name="search"),
    path("ups/", views.Ups, name="ups"),
    path("th/", views.Th, name="th"),
    path("con/", views.Con, name="conn"),
    path("phone_update/<int:pk>/", views.PhoneUpdateView.as_view(), name="phoneupdate"),
]

devices/models.py
from django.db import models
from core import models as core_models
from users import models as users_models
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.


class Abstract(core_models.TimeStampedModel):   #아직 사용x 필요하면 사용예정

    name = models.CharField(max_length=20)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Device(core_models.TimeStampedModel):

    DEVICE_CHOICE = [
        ("ups", "UPS"), ("th", "온습도"), ("con", "접점")
    ]
    SNMP_CHOICE = [
        ("megatec", "MEGATEC"), ("eaton", "EATON"), ("world_wise", "WORLD_WISE")
    ]
    snmp = models.CharField(max_length=20, choices=SNMP_CHOICE, blank=None, default=None)
    name = models.CharField(max_length=50, default="")
    ip = models.GenericIPAddressField(protocol="IPv4", unpack_ipv4=False)
    port_num = models.IntegerField(default=0)
    administrator = models.CharField(max_length=20, default="")
    device_select = models.CharField(max_length=3, choices=DEVICE_CHOICE)
    host = models.ForeignKey(users_models.User, on_delete=models.CASCADE,related_name="devices")

    def __str__(self):
        return f"{self.name}_{self.device_select}"
        

@receiver(post_save, sender=Device)
def device_postsave(sender, instance, created, **kwargs):
    print(instance.device_select)
    print(created)
    device_select = instance.device_select
    if created:
        if device_select == "ups":
            Ups.objects.create(device_name=instance)
        elif device_select == "th":
            Temp_Humi.objects.create(device_name=instance)
        else:
            Contact.objects.create(device_name=instance)
        Phone_Number.objects.create(user=instance)



class Ups(core_models.TimeStampedModel):
    device_name = models.ForeignKey("Device", related_name="upss", on_delete=models.CASCADE)

    ups_model = models.CharField(max_length=50, default="")
    ups_admin = models.CharField(max_length=50, default="(주)뉴피에스")
    ups_location = models.CharField(max_length=50, default="UPS실")

    indent_model = models.CharField(max_length=50, default="")
    input_phase = models.IntegerField(default=0)
    input_fail_cause = models.IntegerField(default=0)
    output_phase = models.IntegerField(default=0)
    output_status = models.IntegerField(default=0)

    input_voltage = models.FloatField(default=0)
    input_voltage_r = models.FloatField(default=0)
    input_voltage_s = models.FloatField(default=0)
    input_voltage_t = models.FloatField(default=0)

    input_current = models.FloatField(default=0)
    input_current_r = models.FloatField(default=0)
    input_current_s = models.FloatField(default=0)
    input_current_t = models.FloatField(default=0)

    input_hz = models.FloatField(default=0)
    input_hz_r = models.FloatField(default=0)
    input_hz_s = models.FloatField(default=0)
    input_hz_t = models.FloatField(default=0)

    output_voltage = models.FloatField(default=0)
    output_voltage_r = models.FloatField(default=0)
    output_voltage_s = models.FloatField(default=0)
    output_voltage_t = models.FloatField(default=0)

    output_current = models.FloatField(default=0)
    output_current_r = models.FloatField(default=0)
    output_current_s = models.FloatField(default=0)
    output_current_t = models.FloatField(default=0)

    output_load = models.IntegerField(default=0)
    output_load_r = models.IntegerField(default=0)
    output_load_s = models.IntegerField(default=0)
    output_load_t = models.IntegerField(default=0)

    output_hz = models.FloatField(default=0)
    output_hz_r = models.FloatField(default=0)
    output_hz_s = models.FloatField(default=0)
    output_hz_t = models.FloatField(default=0)

    bypass_voltage = models.FloatField(default=0)
    bypass_voltage_r = models.FloatField(default=0)
    bypass_voltage_s = models.FloatField(default=0)
    bypass_voltage_t = models.FloatField(default=0)

    bypass_current = models.FloatField(default=0)
    bypass_current_r = models.FloatField(default=0)
    bypass_current_s = models.FloatField(default=0)
    bypass_current_t = models.FloatField(default=0)

    bypass_hz = models.FloatField(default=0)
    bypass_hz_r = models.FloatField(default=0)
    bypass_hz_s = models.FloatField(default=0)
    bypass_hz_t = models.FloatField(default=0)

    ups_temp = models.FloatField(default=0)
    
    battery_voltage = models.FloatField(default=0)
    battery_status = models.IntegerField(default=0)
    battery_current = models.FloatField(default=0)

    class Meta:
        verbose_name_plural = "UPS"

    def __str__(self):
        return f"{self.device_name} -{self.ups_location}({self.ups_model})"
        

class Temp_Humi(core_models.TimeStampedModel):

    device_name = models.ForeignKey("Device", related_name="temps", on_delete=models.CASCADE)
    th_location = models.CharField(max_length=50, default="전산실")
    temp_1 = models.FloatField(default=0)
    temp_2 = models.FloatField(default=0)
    humi_1 = models.FloatField(default=0)
    humi_2 = models.FloatField(default=0)

    class Meta:
        verbose_name_plural = "TEMP_HUMI"

    def __str__(self):
        return f"{self.device_name} - {self.th_location}"
    


class Contact(core_models.TimeStampedModel):

    device_name = models.ForeignKey("Device", related_name="contacts", on_delete=models.CASCADE)
    con_location = models.CharField(max_length=50, default="전산실")
    con_1 = models.IntegerField(default=0)
    con_2 = models.IntegerField(default=0)
    con_3 = models.IntegerField(default=0)
    con_4 = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "Contact"

    def __str__(self):
        return f'{self.device_name} - {self.con_location}'
    


class Phone_Number(core_models.TimeStampedModel):
    
    user = models.OneToOneField("Device", on_delete=models.CASCADE, default=None, blank=True, related_name="phones")
    name_1 = models.CharField(max_length=20, blank=True)
    name_2 = models.CharField(max_length=20, blank=True)
    name_3 = models.CharField(max_length=20, blank=True)
    name_4 = models.CharField(max_length=20, blank=True)
    name_5 = models.CharField(max_length=20, blank=True)
    name_6 = models.CharField(max_length=20, blank=True)
    name_7 = models.CharField(max_length=20, blank=True)
    name_8 = models.CharField(max_length=20, blank=True)
    name_9 = models.CharField(max_length=20, blank=True)
    name_10 = models.CharField(max_length=20, blank=True)

    phone_1 = models.CharField(max_length=11, blank=True)
    phone_2 = models.CharField(max_length=11, blank=True)
    phone_3 = models.CharField(max_length=11, blank=True)
    phone_4 = models.CharField(max_length=11, blank=True)
    phone_5 = models.CharField(max_length=11, blank=True)
    phone_6 = models.CharField(max_length=11, blank=True)
    phone_7 = models.CharField(max_length=11, blank=True)
    phone_8 = models.CharField(max_length=11, blank=True)
    phone_9 = models.CharField(max_length=11, blank=True)
    phone_10 = models.CharField(max_length=11, blank=True)

    class Meta:
        verbose_name_plural = "Phone_Number"
    
    def __str__(self):
        return f'{self.user.name} - {self.user.device_select}'
    

templates/devices/list/items/conn.html
{% block content %}
<div class="mt-2 bg-gray-300 border">
  <h3 class="text-2xl">기타</h3>
</div>
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm lg">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Type
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Status
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Role
              </th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">

            {% for c in con %}
            
            <tr>
              
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="flex items-center">
                    <a href=" {% url 'devices:con_detail' c.pk %}">
                      <div class="flex-shrink-0 h-10 w-10">
                        <img class="h-10 w-10 rounded-full" src="http://www.kjups.com/design/default/images/np02-02.jpg" alt="">
                      </div>
                      <div class="ml-4">
                        <div class="text-sm font-medium text-gray-900">
                          {{c.name}}
                        </div>
                        <div class="text-sm text-gray-500">
                          {{c.administrator}}
                        </div>
                    </a>
                    </div>
                  </div>
                </td>
              
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900">{{c.get_device_select_display}}</div>
                <div class="text-sm text-gray-500">etc...</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  Active
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                {{t.host}}
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <a href=" {% url 'devices:phoneupdate' c.phones.id %} " class="text-indigo-600 hover:text-indigo-900">Edit</a>
              </td>
            </tr>
          
            {% endfor %}
            <!-- More items... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



</div>
{% endblock content %}

templates/devices/list/items/th.html
{% block content %}
<div class="mt-2 bg-gray-300 border">
  <h3 class="text-2xl">온습도</h3>
</div>
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm lg">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-1/4">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Type
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Status
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Role
              </th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">

            {% for t in th %}
            
            <tr>
              
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="flex items-center">
                    <a href=" {% url 'devices:th_detail' t.pk %}">
                      <div class="flex-shrink-0 h-10 w-10">
                        <img class="h-10 w-10 rounded-full" src="http://www.kjups.com/design/default/images/np02-02.jpg" alt="">
                      </div>
                      <div class="ml-4">
                        <div class="text-sm font-medium text-gray-900">
                          {{t.name}}
                        </div>
                        <div class="text-sm text-gray-500">
                          {{t.administrator}}
                        </div>
                    </a>
                    </div>
                  </div>
                </td>
              
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900">{{t.get_device_select_display}}</div>
                <div class="text-sm text-gray-500">etc...</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  Active
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                {{t.host}}
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <a href="{% url 'devices:phoneupdate' t.phones.id %}" class="text-indigo-600 hover:text-indigo-900">연락처</a>
              </td>
            </tr>
          
            {% endfor %}
            <!-- More items... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



</div>
{% endblock content %}

templates/devices/list/items/ups.html
{% block content %}
<div class="mt-2 bg-gray-300 border">
  <h3 class="text-2xl">UPS</h3>
</div>
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm lg ">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider w-1/4">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Type
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Status
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Role
              </th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">

            {% for u in ups %}
            
            <tr>
              
                <td class="px-6 py-4 whitespace-nowrap">
                  <div class="flex items-center">
                    <a href=" {% url 'devices:ups_detail' u.pk %}">
                      <div class="flex-shrink-0 h-10 w-10">
                        <img class="h-10 w-10 rounded-full" src="http://www.kjups.com/design/default/images/np02-02.jpg" alt="">
                      </div>
                      <div class="ml-4">
                        <div class="text-sm font-medium text-gray-900">
                          {{u.name}}
                        </div>
                        <div class="text-sm text-gray-500">
                          {{u.administrator}}
                        </div>
                    </a>
                    </div>
                  </div>
                </td>
              
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900">{{u.get_device_select_display}}</div>
                <div class="text-sm text-gray-500">etc...</div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                  Active
                </span>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                {{u.host}}
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                <a href="{% url 'devices:phoneupdate' u.phones.id %}" class="text-indigo-600 hover:text-indigo-900">연락처</a>
              </td>
            </tr>
          
            {% endfor %}
            <!-- More items... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



</div>

{% endblock content %}