config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("devices/", include("devices.urls", namespace="devices")),
    path("users/", include("users.urls", namespace="users")),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from devices import views as devices_views


app_name = "core"

urlpatterns = [
    path("", devices_views.HomeView, name="home")
]

devices/urls.py
from django.urls import path
from . import views

app_name = "devices"

urlpatterns = [
    path("ups/<int:pk>/", views.Ups_detail, name="ups_detail"),
    path("th/<int:pk>/", views.Th_detail, name="th_detail"),
    path("con/<int:pk>/", views.Con_detail, name="con_detail"),
    # path("Phone/<int:pk>/", views.Phone, name="phone"),
    path("search/", views.Search, name="search"),
    path("ups/", views.Ups, name="ups"),
    path("th/", views.Th, name="th"),
    path("con/", views.Con, name="conn"),
    path("phone_update/<int:pk>/", views.PhoneUpdateView.as_view(), name="phoneupdate"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block page_name %} {% endblock page_name %} |NEWPS_SERVER</title>
    
  </head>
  
  <body class="text-gray-800">


    <header class="flex items-center justify-between px-6 h-20 border-b-2">
      <div class="flex items-center ">
        <a href="{% url 'core:home' %} " class="mr-6">
          <img class="w-32 " src=" {% static 'img/logo.png' %} "/>
        </a>
        {% block search-bar %}
        <form method="GET" action="{% url 'devices:search' %}">
          <input class="border px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-sm w-64 shadow-md hover:shadow-lg focus:outline-none" name="device" placeholder="Search by Device" />
        </form>
        {% endblock search-bar %} 
      </div>
      {% include 'partials/header.html' %}
      
      
      
    </header>
    {% include 'partials/message.html' %}
    
    {%block content %}
    
    {%endblock content %}
    {%include "partials/footer.html" %}
  </body>
</html>